# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jumper < Formula
  desc "A bookmark manager for your shell directories"
  homepage "https://github.com/AmrSaber/jumper"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AmrSaber/jumper/releases/download/v0.3.0/jumper_0.3.0_Darwin_x86_64.tar.gz"
      sha256 "3a3efe65173f41dee45b0454dba2151a426046a75c887ce8f3469590732f34b1"

      define_method(:install) do
        bin.install "jumper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AmrSaber/jumper/releases/download/v0.3.0/jumper_0.3.0_Darwin_arm64.tar.gz"
      sha256 "cf8f9b5b99065fa3dc33af08caa043289b56513ebd3043c748ab517141c46c1d"

      define_method(:install) do
        bin.install "jumper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AmrSaber/jumper/releases/download/v0.3.0/jumper_0.3.0_Linux_x86_64.tar.gz"
      sha256 "b046eb3f292c51bf953dd2725421446c3b6ce839de9a729819f7b48c3288b502"
      define_method(:install) do
        bin.install "jumper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AmrSaber/jumper/releases/download/v0.3.0/jumper_0.3.0_Linux_arm64.tar.gz"
      sha256 "ab17c76cc0ceed86faffdc9706d6f9cc781ae348f20c98d5ce8b01904be252b3"
      define_method(:install) do
        bin.install "jumper"
      end
    end
  end

  def post_install
    system "#{bin}/jumper", "init"
  end

  test do
    system "#{bin}/jumper", "--version"
  end
end
