# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jumper < Formula
  desc "A bookmark manager for your shell directories"
  homepage "https://github.com/AmrSaber/jumper"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AmrSaber/jumper/releases/download/v0.3.2/jumper_0.3.2_Darwin_x86_64.tar.gz"
      sha256 "0a54194d727d168367952f9605e490ff87fc7ceeda94b6b7eba25028eaa457c9"

      define_method(:install) do
        bin.install "jumper"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AmrSaber/jumper/releases/download/v0.3.2/jumper_0.3.2_Darwin_arm64.tar.gz"
      sha256 "c67d201a20605a07e4daff6ceb77fbac90c3a51079f02a3570202c4e12e220cc"

      define_method(:install) do
        bin.install "jumper"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AmrSaber/jumper/releases/download/v0.3.2/jumper_0.3.2_Linux_x86_64.tar.gz"
      sha256 "f3e277fe70a57cb0d80b67217e41c6ad280f13df85731fec72b7e056cb493b4e"
      define_method(:install) do
        bin.install "jumper"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AmrSaber/jumper/releases/download/v0.3.2/jumper_0.3.2_Linux_arm64.tar.gz"
      sha256 "4bd49339ef74bb81483564aaf5e870f58b40372fe6c4fd559634cf17f3aa6448"
      define_method(:install) do
        bin.install "jumper"
      end
    end
  end

  def post_install
    system "#{bin}/jumper", "init"
  end

  test do
    system "#{bin}/jumper", "--version"
  end
end
