# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kv < Formula
  desc "A lightweight, feature-rich command-line key-value store with encryption, TTL, and version control"
  homepage "https://github.com/AmrSaber/kv"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AmrSaber/kv/releases/download/v0.1.4/kv_0.1.4_Darwin_x86_64.tar.gz"
      sha256 "8e3c4dfe159bbaa1094c14537e04f2296ede1a4e0e816a7dabaa1797b144bb2f"

      def install
        bin.install "kv"

        # Install shell completions
        bash_completion.install "completions/kv.bash" => "kv"
        zsh_completion.install "completions/kv.zsh" => "_kv"
        fish_completion.install "completions/kv.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AmrSaber/kv/releases/download/v0.1.4/kv_0.1.4_Darwin_arm64.tar.gz"
      sha256 "0a9fd113d0c5f8d66226664fca37acfaab5a20a223c10c15d49e8fff4d6b3d67"

      def install
        bin.install "kv"

        # Install shell completions
        bash_completion.install "completions/kv.bash" => "kv"
        zsh_completion.install "completions/kv.zsh" => "_kv"
        fish_completion.install "completions/kv.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AmrSaber/kv/releases/download/v0.1.4/kv_0.1.4_Linux_x86_64.tar.gz"
      sha256 "ffd6b395a77ef53fcb4d17913d296b4084f15570a3a82eae0ca4323f0c2e8599"
      def install
        bin.install "kv"

        # Install shell completions
        bash_completion.install "completions/kv.bash" => "kv"
        zsh_completion.install "completions/kv.zsh" => "_kv"
        fish_completion.install "completions/kv.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AmrSaber/kv/releases/download/v0.1.4/kv_0.1.4_Linux_arm64.tar.gz"
      sha256 "fcea750e2d340814a63444670103ef1ac2c19595b20e9aabb02da73615ae4936"
      def install
        bin.install "kv"

        # Install shell completions
        bash_completion.install "completions/kv.bash" => "kv"
        zsh_completion.install "completions/kv.zsh" => "_kv"
        fish_completion.install "completions/kv.fish"
      end
    end
  end

  test do
    system "#{bin}/kv", "--version"
  end
end
