# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kv < Formula
  desc "A lightweight, feature-rich command-line key-value store with encryption, TTL, and version control"
  homepage "https://github.com/AmrSaber/kv"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AmrSaber/kv/releases/download/v0.7.0/kv_0.7.0_Darwin_x86_64.tar.gz"
      sha256 "4df6b12a0362f55c7aa58eb7239e416466d75c02c572bc2c0f573ccec07c929b"

      define_method(:install) do
        bin.install "kv"

        # Install shell completions
        bash_completion.install "completions/kv.bash" => "kv"
        zsh_completion.install "completions/kv.zsh" => "_kv"
        fish_completion.install "completions/kv.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AmrSaber/kv/releases/download/v0.7.0/kv_0.7.0_Darwin_arm64.tar.gz"
      sha256 "e649559fdbaed2f5b99e1ad2a1bfac1e46f92979022d819db0c19294efc0b1a1"

      define_method(:install) do
        bin.install "kv"

        # Install shell completions
        bash_completion.install "completions/kv.bash" => "kv"
        zsh_completion.install "completions/kv.zsh" => "_kv"
        fish_completion.install "completions/kv.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AmrSaber/kv/releases/download/v0.7.0/kv_0.7.0_Linux_x86_64.tar.gz"
      sha256 "2f3f799ccfc6ece753c2a16b019ee41a388515c65c7f29c9be8de927c646ea0a"
      define_method(:install) do
        bin.install "kv"

        # Install shell completions
        bash_completion.install "completions/kv.bash" => "kv"
        zsh_completion.install "completions/kv.zsh" => "_kv"
        fish_completion.install "completions/kv.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AmrSaber/kv/releases/download/v0.7.0/kv_0.7.0_Linux_arm64.tar.gz"
      sha256 "8691a05aa4c4f0524d30c6349358c164b659d1728c03f112f6984b8646606893"
      define_method(:install) do
        bin.install "kv"

        # Install shell completions
        bash_completion.install "completions/kv.bash" => "kv"
        zsh_completion.install "completions/kv.zsh" => "_kv"
        fish_completion.install "completions/kv.fish"
      end
    end
  end

  test do
    system "#{bin}/kv", "--version"
  end
end
