# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kv < Formula
  desc "A lightweight, feature-rich command-line key-value store with encryption, TTL, and version control"
  homepage "https://github.com/AmrSaber/kv"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AmrSaber/kv/releases/download/v0.3.0/kv_0.3.0_Darwin_x86_64.tar.gz"
      sha256 "3a06b76911416dce32e717ede9b61c898ddc2cf9be4b93b1e8f04311817e08bf"

      def install
        bin.install "kv"

        # Install shell completions
        bash_completion.install "completions/kv.bash" => "kv"
        zsh_completion.install "completions/kv.zsh" => "_kv"
        fish_completion.install "completions/kv.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AmrSaber/kv/releases/download/v0.3.0/kv_0.3.0_Darwin_arm64.tar.gz"
      sha256 "7c04d0ce4b506ccffb2b8da158953d4470de167e543bebbb612039a497afa5d0"

      def install
        bin.install "kv"

        # Install shell completions
        bash_completion.install "completions/kv.bash" => "kv"
        zsh_completion.install "completions/kv.zsh" => "_kv"
        fish_completion.install "completions/kv.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AmrSaber/kv/releases/download/v0.3.0/kv_0.3.0_Linux_x86_64.tar.gz"
      sha256 "e227c64d1bd2c585760baaae9e78daadc922c965b3616f0d92259a0e05d1260e"
      def install
        bin.install "kv"

        # Install shell completions
        bash_completion.install "completions/kv.bash" => "kv"
        zsh_completion.install "completions/kv.zsh" => "_kv"
        fish_completion.install "completions/kv.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AmrSaber/kv/releases/download/v0.3.0/kv_0.3.0_Linux_arm64.tar.gz"
      sha256 "04f69a4c6bab911032c6bc8b0b41340ed6199304b2660b52236e93436f865879"
      def install
        bin.install "kv"

        # Install shell completions
        bash_completion.install "completions/kv.bash" => "kv"
        zsh_completion.install "completions/kv.zsh" => "_kv"
        fish_completion.install "completions/kv.fish"
      end
    end
  end

  test do
    system "#{bin}/kv", "--version"
  end
end
