# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Random < Formula
  desc "CLI tool to generate random data"
  homepage "https://github.com/AmrSaber/random"
  version "3.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AmrSaber/random/releases/download/v3.0.2/random_3.0.2_darwin_amd64.tar.gz"
      sha256 "059549ffae322a14b0154e6e2e6ae90127818ad3fec9edc88abf04a4d9e0251e"

      def install
        bin.install "random"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AmrSaber/random/releases/download/v3.0.2/random_3.0.2_darwin_arm64.tar.gz"
      sha256 "2857d62b7ca6b0e888f2052f9fcae40886de6f379318dc8789ce081bc3209960"

      def install
        bin.install "random"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AmrSaber/random/releases/download/v3.0.2/random_3.0.2_linux_amd64.tar.gz"
      sha256 "c63a5901f1e50496a705a2101a40b38b0c993b6034c3d2af3a9b8b0c864a81f1"
      def install
        bin.install "random"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AmrSaber/random/releases/download/v3.0.2/random_3.0.2_linux_arm64.tar.gz"
      sha256 "83c0666940504ac8b2e3ac32ea631a8882421179d9ec8a19944a80021a92f5b8"
      def install
        bin.install "random"
      end
    end
  end

  test do
    system "#{bin}/random", "--help"
  end
end
