# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Random < Formula
  desc "CLI tool to generate random data"
  homepage "https://github.com/AmrSaber/random"
  version "3.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AmrSaber/random/releases/download/v3.0.3/random_3.0.3_darwin_amd64.tar.gz"
      sha256 "c0748a2648c1a43a11d97da865be3e85193e96682424718ce80427ae2bb17fd1"

      define_method(:install) do
        bin.install "random"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AmrSaber/random/releases/download/v3.0.3/random_3.0.3_darwin_arm64.tar.gz"
      sha256 "52430e3adc1df80bacf5b76a90330c711aa23e6f5e1f8066dbb10e7277874300"

      define_method(:install) do
        bin.install "random"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AmrSaber/random/releases/download/v3.0.3/random_3.0.3_linux_amd64.tar.gz"
      sha256 "e43e142ab91440e27968c2bbf7485232b75ec9f3b089db5a3667a9874d361bc7"
      define_method(:install) do
        bin.install "random"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AmrSaber/random/releases/download/v3.0.3/random_3.0.3_linux_arm64.tar.gz"
      sha256 "674c6d061b320d95fefbe2c2c7a8103926b2416c94af05ed7125635eb997f4ca"
      define_method(:install) do
        bin.install "random"
      end
    end
  end

  test do
    system "#{bin}/random", "--help"
  end
end
