# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Random < Formula
  desc "CLI tool to generate random data"
  homepage "https://github.com/AmrSaber/random"
  version "3.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AmrSaber/random/releases/download/v3.0.1/random_3.0.1_darwin_amd64.tar.gz"
      sha256 "6846cfdbd00ce9925398cd7462a3105c4f84c72afc487a103298baa0ba5fbb9f"

      def install
        bin.install "random"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AmrSaber/random/releases/download/v3.0.1/random_3.0.1_darwin_arm64.tar.gz"
      sha256 "7d23efcba0174b3d9eafd49e2bb58b3b87d558f40d6e4ef0f4803679a444e463"

      def install
        bin.install "random"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AmrSaber/random/releases/download/v3.0.1/random_3.0.1_linux_amd64.tar.gz"
      sha256 "410598f5cabf4fdfad31333d8905a1292c0d323a111d0872389590d9340a8a27"
      def install
        bin.install "random"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AmrSaber/random/releases/download/v3.0.1/random_3.0.1_linux_arm64.tar.gz"
      sha256 "7e3640bf0ba715da9337bad4f56ee1a398773f2000d8fde9768235cfa3a2d2c6"
      def install
        bin.install "random"
      end
    end
  end

  test do
    system "#{bin}/random", "--help"
  end
end
