# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Timer < Formula
  desc "A simple command-line timer"
  homepage "https://github.com/AmrSaber/timer"
  version "1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AmrSaber/timer/releases/download/v1.3/timer_1.3_Darwin_x86_64.tar.gz"
      sha256 "af033f04de2c0b75dceeed8744dc793d41327bce9db2dc2279f9718896575f9e"

      define_method(:install) do
        bin.install "timer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AmrSaber/timer/releases/download/v1.3/timer_1.3_Darwin_arm64.tar.gz"
      sha256 "36c549492f09aee91a04f2b71adab5a5bcbac0e00dc9c870c876ab5edd4dc140"

      define_method(:install) do
        bin.install "timer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AmrSaber/timer/releases/download/v1.3/timer_1.3_Linux_x86_64.tar.gz"
      sha256 "d08d111d5c0d40ddceb58c376156c8b9696a266ef5ee1a5be4d6aacc66a796ec"
      define_method(:install) do
        bin.install "timer"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/AmrSaber/timer/releases/download/v1.3/timer_1.3_Linux_armv6.tar.gz"
      sha256 "dafc7d6c86be06cdff0fda8bf7a1589ed6be6f28abafbcb857f5158eecc9bceb"
      define_method(:install) do
        bin.install "timer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AmrSaber/timer/releases/download/v1.3/timer_1.3_Linux_arm64.tar.gz"
      sha256 "a008347cdff943e31d272601a5c527cd55e2d608713b8a83871bec94a638f091"
      define_method(:install) do
        bin.install "timer"
      end
    end
  end

  test do
    system "#{bin}/timer", "0"
  end
end
