# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Timer < Formula
  desc "A simple command-line timer"
  homepage "https://github.com/AmrSaber/timer"
  version "1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AmrSaber/timer/releases/download/v1.2/timer_1.2_Darwin_x86_64.tar.gz"
      sha256 "1c539da596bd248721d7864aa3b4333d372611f1b1cbe5fa18f93b6ed8d9a5b4"

      define_method(:install) do
        bin.install "timer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AmrSaber/timer/releases/download/v1.2/timer_1.2_Darwin_arm64.tar.gz"
      sha256 "88ddbcdff94b11180d8e0cf3ad49190cd72144d5746c0e08155c08820ca8724b"

      define_method(:install) do
        bin.install "timer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AmrSaber/timer/releases/download/v1.2/timer_1.2_Linux_x86_64.tar.gz"
      sha256 "8d10d42c8ea0341942481a2ea8bf0a6910ec10a697d1fe674b2f49e7a25987d8"
      define_method(:install) do
        bin.install "timer"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/AmrSaber/timer/releases/download/v1.2/timer_1.2_Linux_armv6.tar.gz"
      sha256 "6d931ab9708f6750696d774eecde2a5ef88354d24bfdf0c761b59a4e28b244e1"
      define_method(:install) do
        bin.install "timer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AmrSaber/timer/releases/download/v1.2/timer_1.2_Linux_arm64.tar.gz"
      sha256 "0e847a3bbc18d90fd4ffb041d83e2cab1a6c0c0bf96f93677bb0f73c11f2ac81"
      define_method(:install) do
        bin.install "timer"
      end
    end
  end

  test do
    system "#{bin}/timer", "0"
  end
end
