# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Timer < Formula
  desc "A simple command-line timer"
  homepage "https://github.com/AmrSaber/timer"
  version "1.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AmrSaber/timer/releases/download/v1.3.1/timer_1.3.1_Darwin_x86_64.tar.gz"
      sha256 "b9afacbf328b5ab6bdd122f48bb6dd26ecdfee21a8f64a3de7e1562974106d2b"

      define_method(:install) do
        bin.install "timer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AmrSaber/timer/releases/download/v1.3.1/timer_1.3.1_Darwin_arm64.tar.gz"
      sha256 "dc4f43c1d31149240d7ffdd1ef96f9cfd9aa9f8049bdde6974f7939bf5844365"

      define_method(:install) do
        bin.install "timer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AmrSaber/timer/releases/download/v1.3.1/timer_1.3.1_Linux_x86_64.tar.gz"
      sha256 "90bb474ac4be77e90feaeb884ebcb160278197c8751b1263be60f5b659edd394"
      define_method(:install) do
        bin.install "timer"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/AmrSaber/timer/releases/download/v1.3.1/timer_1.3.1_Linux_armv6.tar.gz"
      sha256 "5818dcfecf97d30bb7c4c4fcfeef50e4fcf592bcf96d6530a7d4f28fc4dc70e2"
      define_method(:install) do
        bin.install "timer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AmrSaber/timer/releases/download/v1.3.1/timer_1.3.1_Linux_arm64.tar.gz"
      sha256 "78d5384eb6c4c1cbc62d904c5c6896ff03c054a2ee1fdd1fb11d7044b8826ca6"
      define_method(:install) do
        bin.install "timer"
      end
    end
  end

  test do
    system "#{bin}/timer", "--version"
  end
end
