# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcp-gateway" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "efd80be1fca4dde9a3c1f70eed9d5c83ce0bcdd638bf2289926ef8a8c6fa640f"
      url "https://github.com/AmrSaber/mcp-gateway/releases/download/v#{version}/mcp-gateway_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3bb9f21531671e9785a8c1ef5ecd0054a33b53e8f6c74abf233f9482e8762eac"
      url "https://github.com/AmrSaber/mcp-gateway/releases/download/v#{version}/mcp-gateway_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "71f8557689802de95872d565a02240c9e2564cd490350d2e3c09e8a28e2e69ac"
      url "https://github.com/AmrSaber/mcp-gateway/releases/download/v#{version}/mcp-gateway_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "7f790c121b596863fa60a0b5fa8e1d73b817e993e63df14e2c632e9f62d217b7"
      url "https://github.com/AmrSaber/mcp-gateway/releases/download/v#{version}/mcp-gateway_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "mcp-gateway"
  desc "A single MCP server that fronts many others, keeping their tool schemas out of the agent's context"
  homepage "https://github.com/AmrSaber/mcp-gateway"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcp-gateway"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mcp-gateway"]
    end
  end

  # No zap stanza required

end
