# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcp-gateway" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "9fce1d1f96c94a24af7b0255e2f2e25908c7ff9b88aa85b506e4ee0c785302e4"
      url "https://github.com/AmrSaber/mcp-gateway/releases/download/v#{version}/mcp-gateway_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c4f47563f8f6dbe11fd4396815002bb6baa0eb43d27bf1025a74cea18f063295"
      url "https://github.com/AmrSaber/mcp-gateway/releases/download/v#{version}/mcp-gateway_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "616ab44b540283165e70e87aeb3fa55d948c5559177c366a2c696a8141ed31ab"
      url "https://github.com/AmrSaber/mcp-gateway/releases/download/v#{version}/mcp-gateway_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "c48bb4ed0475e7c1522d4a3431befb010de5ed835fb0fde0728ee4fc2be5858a"
      url "https://github.com/AmrSaber/mcp-gateway/releases/download/v#{version}/mcp-gateway_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "mcp-gateway"
  desc "A single MCP server that fronts many others, keeping their tool schemas out of the agent's context"
  homepage "https://github.com/AmrSaber/mcp-gateway"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcp-gateway"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mcp-gateway"]
    end
  end

  # No zap stanza required

end
