# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcp-gateway" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "27c6e1c541ab4947dd1ccb1392b536212865fda65feb8bc8cef8da8fab50eb1b"
      url "https://github.com/AmrSaber/mcp-gateway/releases/download/v#{version}/mcp-gateway_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "b2aa1f9ea0c95a5cced0d3ba5f656d0a5ee996544ee483b31091bde7ca634139"
      url "https://github.com/AmrSaber/mcp-gateway/releases/download/v#{version}/mcp-gateway_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b3f4c8c5a360c4a4d87764f6b0e71f90de560a3c2d1c1b495d87c457ef7e69d4"
      url "https://github.com/AmrSaber/mcp-gateway/releases/download/v#{version}/mcp-gateway_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "2f782ecb7456bd70df1ba3559a856cac412746032905121ee0a625431eb42d9c"
      url "https://github.com/AmrSaber/mcp-gateway/releases/download/v#{version}/mcp-gateway_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "mcp-gateway"
  desc "A single MCP server that fronts many others, keeping their tool schemas out of the agent's context"
  homepage "https://github.com/AmrSaber/mcp-gateway"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcp-gateway"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mcp-gateway"]
    end
  end

  # No zap stanza required

end
